version: '3.1'

services:
  mongo:
    image: postgres:latest
    restart: always
    volumes:
      - /data/db/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
